import { v4 as uuidv4 } from "uuid";

export const checkoutFormData = [
    {
        id: "pincode",
        name: "pincode",
        label: "Enter Pincode",
        type: "number",
        size: "small",
        fullWidth: false,
        helperText: "",
        required: true,
    },
    {
        id: "firstname",
        name: "firstname",
        label: "Enter First Name",
        type: "text",
        size: "small",
        fullWidth: false,
        helperText: "",
        required: true,
    },
    {
        id: "lastname",
        name: "lastname",
        label: "Enter Last Name",
        type: "text",
        size: "small",
        fullWidth: false,
        helperText: "",
        required: true,
    },
    {
        id: "flatno",
        name: "flatno",
        label: "Enter Flat/House No/Floor/Building Name",
        type: "text",
        size: "small",
        fullWidth: true,
        helperText: "",
        required: true,
    },
    {
        id: "street",
        name: "street",
        label: "Enter Colony/Street",
        type: "text",
        size: "small",
        fullWidth: true,
        helperText: "",
        required: true,
    },{
        id: "landmark",
        name: "landmark",
        label: "Enter Landmark",
        type: "text",
        size: "small",
        fullWidth: true,
        helperText: "",
        required: false,
    },
    {
        id: "city",
        name: "city",
        label: "Enter City",
        type: "text",
        size: "small",
        fullWidth: false,
        helperText: "",
        required: true,
    },
    {
        id: "state",
        name: "state",
        label: "Enter State",
        type: "text",
        size: "small",
        fullWidth: false,
        helperText: "",
        required: true,
    },
    {
        id: "mobileno",
        name: "mobileno",
        label: "Enter Mobile Number",
        type: "number",
        size: "small",
        fullWidth: false,
        helperText: "",
        required: true,
    },
    {
        id: "landlineno",
        name: "landlineno",
        label: "Enter Landline Number",
        type: "number",
        size: "small",
        fullWidth: false,
        helperText: "",
        required: false,
    }
];